=begin
#API whatsgate.ru

#Интерфейс для взаимодействия с клиентом Whatsapp

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.35
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/any_ofseen_body_recipient'
require 'swagger_client/models/any_ofsend_body_message'
require 'swagger_client/models/any_ofsend_body_recipient'
require 'swagger_client/models/check_body'
require 'swagger_client/models/error'
require 'swagger_client/models/getchats_body'
require 'swagger_client/models/getmedia_body'
require 'swagger_client/models/inline_response_200'
require 'swagger_client/models/inline_response_200_1'
require 'swagger_client/models/inline_response_200_2'
require 'swagger_client/models/inline_response_200_3'
require 'swagger_client/models/inline_response_200_4'
require 'swagger_client/models/media'
require 'swagger_client/models/message_media'
require 'swagger_client/models/message_text'
require 'swagger_client/models/one_ofinline_response_200_result'
require 'swagger_client/models/recipient_id'
require 'swagger_client/models/recipient_num'
require 'swagger_client/models/response_async'
require 'swagger_client/models/response_chat'
require 'swagger_client/models/response_chat_group_metadata'
require 'swagger_client/models/response_chat_group_metadata_participants'
require 'swagger_client/models/response_message'
require 'swagger_client/models/seen_body'
require 'swagger_client/models/send_body'

# APIs
require 'swagger_client/api/_api'
require 'swagger_client/api/__api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
